### ISSUE TITLE
Please add license

### ISSUE THREAD

**Issue by asimaranov** [itsu-dev/jvm-on-typescript#3]
Hi. I have a petproject intended to make old j2me games available in browser. I decompiled and rewrited in kotlin some games, but now I want to try to create the runtime on typescript that will support all the games without rewriting by hand. Some parts of your vm will be useful.
Btw maybe you will be interested in the project? I'm also a third year student. Do you have any social networks, maybe telegram? I can show more of my experiments
https://user-images.githubusercontent.com/25568730/201519844-f2902ae6-ced0-4425-bc6c-5a740a726bca.mp4

**Comment by itsu-dev** [comment]
Hi, @asimaranov ! Thank you for your interest. 
I welcome your awesome project, but I worry whether this project can be useful for your project for below reasons:

1. **This project is archived**
This project is outdated and archived. Now I have started to the extended project. The new project supports all features defined in [The Java Virtual Machine Specification -Java SE 8 Edition-](https://docs.oracle.com/javase/specs/jvms/se8/html/index.html). It might be useful, but unfortunately there is no schedule to make it open-source for some reasons (sorry...).

2. **Does not support Java Standard Library, and GUI features**
Because this project is for just researching, this project does not support main Java features including Standard Library or GUI features. But you can implement these features, so if you want, clone (or fork) this repository and develop it! (The new version supports Java Standard Library defined in rt.jar and DOM processing!)

Now I added MIT License. And I want you to write my id in the credit if you use this project.
I'm intended to make the new project open-source somedays! Please wait. And somedays, please show me your attractive project!
